### PR TITLE
Added install guide for Adafruit Macropad

### PR DESCRIPTION
**Pull request by Fescron**

### CODE REVIEW

**Comment by Neradoc** [comment]
So, these are specific installation instructions for the Hotkeys demo script and the adafruit_macropad library.
I think the better move would be to change (PR) the macropad library to accept a layout and keycode modules at init.
The hotkeys guide could then contain a paragraph on how to do that, if we ask politely.
There would also be an example script in this repo for using the macropad library.

**Comment by Fescron** [comment]
Correct, I (living in Belgium, using AZERTY keyboards) recently bought a Macropad and these where the instructions I needed to perform to be able to install and use your code. Since I was not the only one with this need (other people in a "make" group I'm in also posed this question) I figured I'd write a quick guide with the changes I've done to get it working and also try to include it in your repo to help more people.

I certainly agree that it would be way better to ask for better integration for custom layouts without having to modify the library-files ourselves to get it to work. Since I had no prior MicroPython knowledge until a few days ago I did it like I described in the guide, that seemed to be the "best" because I did not need to try to re-write the layout files from Adafruit but only struggled a bit to correctly include your files, hence the "need" for a guide IMO.


"There would also be an example script in this repo for using the macropad library." > Do you mean there is currently something on your repo that somewhat resembles my guide? Because I could not seem to find it and the comments in the Adafruit MicroPython Layout files also did not really help me...

**Comment by Neradoc** [comment]
Version 2.1.0 and later of adafruit_macropad now let you setup the layout and keycode classes to be used:
https://github.com/adafruit/Adafruit_CircuitPython_MacroPad/blob/main/examples/macropad_keyboard_layout.py

```py
from adafruit_macropad import MacroPad

from keyboard_layout_win_fr import KeyboardLayout
from keycode_win_fr import Keycode

macropad = MacroPad(
    layout_class=KeyboardLayout,
    keycode_class=Keycode,
)
```

For the hotkeys project, macros can use the `adafruit_macropad.keycodes` module level variable to use the key names that are setup in `code.py`.
```diff
- from adafruit_hid.keycode import Keycode
+ from adafruit_macropad import keycodes as Keycode
```
I've added that information in a dedicated readme file.

**Comment by Fescron** [comment]
Very nice, thank you!

**Pull request closed without merging**
